#!/bin/bash
# Generated by Omni-Coder Kit — >om:plan (Market Trends)
# Project: HODLISMA | Date: 2026-05-14
set -e

echo "🚀 Setup Market Trends infrastructure..."

# --- [1/2] Verify dependencies ---
echo "📦 [1/2] Checking dependencies..."
DEPS=("recharts" "@tanstack/react-query" "react-markdown" "@ai-sdk/google")
ALL_OK=true
for dep in "${DEPS[@]}"; do
  if node -e "require('$dep')" 2>/dev/null; then
    echo "  ✓ $dep"
  else
    echo "  ✗ $dep — run: npm install $dep"
    ALL_OK=false
  fi
done

if [ "$ALL_OK" = false ]; then
  echo "❌ Missing dependencies. Run npm install first."
  exit 1
fi

# --- [2/2] SQL Migration ---
echo ""
echo "📋 [2/2] SQL Migration for watchlist + price_alerts tables"
echo "   Chạy SQL sau trong Supabase Dashboard → SQL Editor:"
echo ""
cat << 'SQL'
-- ================================================
-- Market Trends: watchlist + price_alerts tables
-- Run in Supabase Dashboard → SQL Editor
-- ================================================

-- 1. Watchlist table
CREATE TABLE IF NOT EXISTS public.watchlist (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  symbol text NOT NULL,
  name text NOT NULL,
  added_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE(user_id, symbol)
);

-- 2. Price Alerts table
CREATE TABLE IF NOT EXISTS public.price_alerts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  symbol text NOT NULL,
  condition text NOT NULL CHECK (condition IN ('above', 'below')),
  target_price numeric NOT NULL,
  is_triggered boolean DEFAULT false NOT NULL,
  triggered_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 3. RLS Policies
ALTER TABLE public.watchlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.price_alerts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own watchlist"
  ON public.watchlist FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own watchlist"
  ON public.watchlist FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own watchlist"
  ON public.watchlist FOR DELETE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can view own alerts"
  ON public.price_alerts FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own alerts"
  ON public.price_alerts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own alerts"
  ON public.price_alerts FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own alerts"
  ON public.price_alerts FOR DELETE
  USING (auth.uid() = user_id);

-- 4. Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.watchlist;
ALTER PUBLICATION supabase_realtime ADD TABLE public.price_alerts;

-- 5. Indexes
CREATE INDEX IF NOT EXISTS idx_watchlist_user_id ON public.watchlist(user_id);
CREATE INDEX IF NOT EXISTS idx_price_alerts_user_id ON public.price_alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_price_alerts_active ON public.price_alerts(user_id) WHERE is_triggered = false;
SQL

echo ""
echo "✅ Setup check complete. Copy SQL above → Supabase Dashboard → SQL Editor → Run."
